### ISSUE TITLE
Error al leer el archivo .tbl

### ISSUE THREAD

**Issue by joxerg** [pachi/hulc2envolventecte#2]
Hola @pachi usando la versión de 29 octubre me da este error, alguna idea?
Gracias,

![CAPT-0012](https://user-images.githubusercontent.com/28994304/70337681-e0b82600-184b-11ea-8c7a-d65d45e2fba6.png)

**Comment by pachi** [comment]
Hola José Luis. Creo que el error se debe a un cambio de formato numérico en el archivo .tbl (usa comas en lugar de puntos, aunque esto ya ha sido corregido en HULC).
He publicado otra versión (v1.4.0) que lee también ese formato.
¿Puedes comprobar que te funciona correctamente?

**Comment by joxerg** [comment]
Rafa funciona perfecto con la 1.4, muchas gracias ;)
